### ISSUE TITLE
机器人戳别人报错(不影响使用)

### ISSUE THREAD

**Issue by As-Kirito** [Dituon/petpet#17]
用了论坛的AutoGroup插件，被戳有概率反击，反击后报错<img width="907" alt="截屏2022-06-09 19 02 12" src="https://user-images.githubusercontent.com/57739158/172832629-4b33835f-1eaf-41ed-8ec1-718f20488d69.png">

**Comment by Dituon** [comment]
问题出现在: **机器人戳别人的事件也会被监听**

将在下一个版本中修复
