### ISSUE TITLE
marry指令相关建议

### ISSUE THREAD

**Issue by YoinSama** [Dituon/petpet#36]
marry指令生成的图，文本气泡经常会挡住头像or图片里的脸（如图1），是否能有一个无文本气泡版本只留结婚申请书的版本？或者增加两块文本气泡之间的间距（参考如图2）
图1：
![BM(U%HEMVS_TUP0_A4XJ1OF](https://user-images.githubusercontent.com/87885299/179476909-752214d5-8e73-4f1b-a287-01c075bc3ba0.png)
图2
![H_(%T`B7~ 3@)F OA19F8ZQ](https://user-images.githubusercontent.com/87885299/179477386-b1aa8844-7f5e-42b3-bd7c-9592542ae95b.png)

**Comment by Dituon** [comment]
已更新, 不满意可自行编辑, 推荐使用超赞的[在线编辑器](https://dituon.github.io/petpet/editor/)

- 删掉`marry`文件夹并重启插件, (`3.7`版本后, 确保启用自动更新)
- 或手动下载更新

~~有更好的方案欢迎提交~~
