### ISSUE TITLE
Petpet Editor在编辑GIF类型图片时，可以分别保存每帧的头像坐标吗

### ISSUE THREAD

**Issue by YoinSama** [Dituon/petpet#45]
编辑器已经实现的是上传图片所有帧共用已添加的头像坐标，这样合适静态图片或者不需要头像坐标频繁变化的GIF图片，
但是如果编辑一些有些需要头像位置频繁移动的gif时，效果就不会很好（例如petpet已有的fencing击剑）。
所以有了分别保存GIF图片每一帧已有头像坐标这个想法。

非常感谢大佬
辛苦了

**Comment by Dituon** [comment]
~~看了好几遍  没看懂~~

能否举例说明 或补充详细信息

**Comment by YoinSama** [comment]
不好意思，是我表达的不准确。

我用一个GIF举个例子吧：

这是这个GIF的第一帧：

![5)@RLNMD)N8{WW7T2RTA18J](https://user-images.githubusercontent.com/87885299/183837875-afd52547-0324-4be2-8063-5da069de4aa3.png)

我添加了两个头像盖住了原图的头部。

但是当图片播放来到第五帧的时候（因为第五帧运动幅度相对更大，所以用第五帧来举例）：

![T0$@@B1M6TNK@HXFISZ8YPA](https://user-images.githubusercontent.com/87885299/183838260-e33beab4-bb8a-4b75-95c4-92129b54d3f9.png)

因为图片中人物头部的移动，导致第一帧原来坐标的头像挡不住第五帧人物头部了。
此时我就将头像位置进行调整：

![6{HPRH_67AHP2 X DE3Q}X](https://user-images.githubusercontent.com/87885299/183838860-bbda769f-48be-4d61-8156-625fc4e7e78c.png)

但是我回到第一帧的时候，头像位置也改变了，头像没盖住第一帧人物的头部：

![_IYRQ9T8R N_V{)%K5 7RS](https://user-images.githubusercontent.com/87885299/183839303-0e9c2e03-a3d1-489e-bd59-de996ac164c2.png)

按现在这个逻辑来看，是一个GIF里所有的帧都共用已添加头像的坐标。我在第一帧加的头像，播放到了第五帧，头像还是还是在第一帧的位置。

以前可能没表达清楚，综上所述我的想法就是：
图片的每一帧，可以保存一个头像坐标。
不会因为在某一帧对头像坐标进行修改之后，别的帧的头像坐标也会一起变得和它一样。

谢谢大佬看完

**Comment by Dituon** [comment]
你可以点击`BuildData`获取构建后的数据

当头像移动时, 编辑器会记录下头像在当前帧中的坐标, 每一帧相互独立, 不会干扰

**Comment by YoinSama** [comment]
原来是这样，我只看着编辑界面了，没注意构建之后的数据有变化，抱歉。非常感谢解答！
