### ISSUE TITLE
配置文件里的disabledGroups没有生效

### ISSUE THREAD

**Issue by SisCleaire** [Dituon/petpet#46]
用配置文件禁用的群聊仍然可以使用插件
配置文件里的格式为：
`disabledGroups: [群号]`

此外试着使用下面这几个权限指令后发现也无法禁用
`/perm cancel * xmmt.dituon.petpet:*`
`/perm cancel g群号 xmmt.dituon.petpet:*`
`/perm permit m群号.* xmmt.dituon.petpet:*`

然后已知群主/管理可以使用 pet on/off 可以启用/禁用 戳一戳
感觉可以再添加一个 petpet on/off 在该群启用/禁用插件所有功能

**Comment by Dituon** [comment]
1. 为照顾不使用`MCL`的用户, 本插件暂不提供权限组
2. 对于禁用策略, 可修改`disablePolicy`配置项(详见`README.md`)

**Comment by Dituon** [comment]
下个版本会将`disablePolicy`默认值更改为`FULL`

**Comment by SisCleaire** [comment]
佬好快的回复
pet off 的禁用策略已经修改并解决了

disabledGroups发现格式如下会生效
`disabledGroups: - 群号`
想问一下添加多个群号的格式要怎样书写呢

**Comment by SisCleaire** [comment]
解决力，谢谢佬
