### ISSUE TITLE
将图片置于底层后，字体就不能放在顶层了

### ISSUE THREAD

**Issue by Huaxidesu** [Dituon/petpet#49]
希望可以让图在底层的同时字在顶层

**Comment by Dituon** [comment]
画图时Text应该位于最顶层，请给出样本便于复现bug

**Comment by Huaxidesu** [comment]
![image](https://user-images.githubusercontent.com/45794248/185722908-2725e0e7-dd87-4fbd-8f01-e817732b7629.png)
{
    "type": "IMG",
    "avatar": [{
        "type": "TO",
        "pos": [39,35,116,116],
        "style": [GRAY],
        "round": false,
        "avatarOnTop": false
    }],
    "text": [{
        "text": "petpet!",
        "pos": [24,25],
        "color": "#191919",
        "size": 9
    }]
}

**Comment by Dituon** [comment]
在线编辑器和插件是用不同的编程语言编写的，在处理图像时也采用不同的算法。

在线编辑器和插件生成的图像有差异为正常现象，以插件结果为准
