### ISSUE TITLE
灰度化参数GRAY貌似无法使用

### ISSUE THREAD

**Issue by Huaxidesu** [Dituon/petpet#50]
`{
    "type": "IMG",
    "avatar": [{
        "type": "TO",
        "pos": [42,37,115,115],
        "style": [GRAY],
        "round": false,
        "avatarOnTop": false
    }],
    "text": [],
    "alias": ["123123"],
    "inRandomList": false
}`
出错的脚本

**Comment by Dituon** [comment]
"style": ["GRAY"]
