### ISSUE TITLE
New feat: Add customize cooldown

### ISSUE THREAD

**Issue by WindsorMacmillan** [Dituon/petpet#6]
群友太爱用了 一次要处理好几个动图 自己电脑挂bot实在遭不住了 希望加个冷却 比如一分钟只接受一个指令这样的

**Comment by Dituon** [comment]
插件的效率非常高，经测试，在主频1.8G的情况下合成一张petpet仅需0.04ms

目前可以尝试降低触发概率，设置不可触发的指令来实现此功能

若未来有同类的issue，会考虑增加此功能
