### ISSUE TITLE
希望增加全局的限定时间内相应次数限制

### ISSUE THREAD

**Issue by Huaxidesu** [Dituon/petpet#60]
群友经常一下发很多，插件相应每一个操作，于是乎机器人就被腾讯风控了，一天得手动解除数次。所以希望增加全局同一时间内相应次数限制来防止机器人被风控

**Comment by Dituon** [comment]
参见 #54 #55 

冷却功能已更新，但需要自行编译

因更新内容较少，暂不提供打包版本

**Comment by WhitrayHB** [comment]
#61 添加了群聊全局CD

**Comment by Dituon** [comment]
https://github.com/Dituon/petpet/releases/tag/4.9
