### ISSUE TITLE
配置文件目录不当

### ISSUE THREAD

**Issue by wenxuanjun** [Dituon/petpet#7]
如题，或许将配置文件置于`Mirai/config/xmmn.dituon.Petpet`目录下，图片资源置于`Mirai/data/xmmn.dituon.Petpet`目录下更为合适。

**Comment by Dituon** [comment]
已更新，使用 `2.0`

**Comment by hundun000** [comment]
@Dituon 你可以看看[这段文档](https://github.com/mamoe/mirai/blob/9d18d79d66c83608fd659d769b8f465a8d604cc8/mirai-console/docs/plugin/JVMPlugin.md#%E7%89%A9%E7%90%86%E7%9B%AE%E5%BD%95%E8%B7%AF%E5%BE%84)

不止是要改成`data/xmmn.dituon.Petpet/sub`，还应该通过plugin.resolveDataFile("sub")来取得
