### ISSUE TITLE
现在读取图片的路径似乎不太对

### ISSUE THREAD

**Issue by milanor1970** [Dituon/petpet#70]
刚才重新下载更新后的版本后加载时得到了如下结果：
“ C:\Users\Administrator\Desktop\Mirai\data\PetPet\xmmt.dituon.petpet\data.json (系统找不到指定的文件。)”
我观察图片的目录data.json似乎应该在更下一级？

**Comment by Dituon** [comment]
请给出完整报错

**Comment by milanor1970** [comment]
> 

`Petpet GifMakerThreadPoolSize: 2
ヾ(≧▽≦*)o Petpet 初始化成功，使用 pet 以获取keyList!
无法读取 C:\Users\Administrator\Desktop\Mirai\data\PetPet\xmmt.dituon.petpet/data.json:

java.io.FileNotFoundException: C:\Users\Administrator\Desktop\Mirai\data\PetPet\xmmt.dituon.petpet\data.json (系统找不到指定的文件。)
Petpet 加载完毕 (共 0 素材，随机表列包含 0 素材，已禁用 0)`
准确的说没有错误，插件正常加载了，但是没有读到图片素材。

**Comment by Dituon** [comment]
图片资源应位于
`Mirai/data/xmmt.dituon.petpet/`目录下

**Comment by milanor1970** [comment]
> 图片资源应位于 `Mirai/data/xmmt.dituon.petpet/`目录下

但是data.json的路径应该是“Mirai/data/xmmt.dituon.petpet/某个图片文件夹/data.json”是不是？

**Comment by Dituon** [comment]
> > 图片资源应位于 `Mirai/data/xmmt.dituon.petpet/`目录下
> 
> 但是data.json的路径应该是“Mirai/data/xmmt.dituon.petpet/某个图片文件夹/data.json”是不是？

是,   如果仍有疑问 请再次阅读文档 或删除`Mirai/data/xmmt.dituon.petpet/`目录以触发自动更新

**Comment by milanor1970** [comment]
这样，我删除了目录，然后启动，它在data下生成了一个Petpet的空目录然后会提示：
`ヾ(≧▽≦*)o Petpet 初始化成功，使用 pet 以获取keyList!
无法读取文件，请检查data目录
Petpet 加载完毕 (共 0 素材，随机表列包含 0 素材，已禁用 0)`
我再次给图片资源放进去则是上一个回答的输出内容。
因为“data.json”文件本身就不在“xmmt.dituon.petpet”路径下而是在"xmmt.dituon.petpet\**某个图片目录**\data.json"下才对？

**Comment by Dituon** [comment]
![image](https://user-images.githubusercontent.com/68615161/197341292-7608698d-d187-4c8a-93ef-3a3c966b2279.png)

**Comment by milanor1970** [comment]
![image](https://user-images.githubusercontent.com/38748546/197342368-69e917b6-77b4-48c4-8258-a012dce29177.png)
这是我目前的目录，其他插件目前运行良好....

**Comment by Dituon** [comment]
> ![image](https://user-images.githubusercontent.com/38748546/197342368-69e917b6-77b4-48c4-8258-a012dce29177.png) 这是我目前的目录，其他插件目前运行良好....

将`Mirai/data/PetPet/xmmt.dituon.petpet/`

移动到`Mirai/data/xmmt.dituon.petpet/`

**Comment by milanor1970** [comment]
> > ![image](https://user-images.githubusercontent.com/38748546/197342368-69e917b6-77b4-48c4-8258-a012dce29177.png) 这是我目前的目录，其他插件目前运行良好....
> 
> 将`Mirai/data/PetPet/xmmt.dituon.petpet/`
> 
> 移动到`Mirai/data/xmmt.dituon.petpet/`
> 
> ![image](https://user-images.githubusercontent.com/68615161/197342631-65f77d6c-bd2f-4122-a43d-55add77023bb.png)

我试过了，上面也提到了这一点，
当文件的路径是“Mirai/data/xmmt.dituon.petpet/” 返回的信息是：`ヾ(≧▽≦*)o Petpet 初始化成功，使用 pet 以获取keyList! 无法读取文件，请检查data目录 Petpet 加载完毕 (共 0 素材，随机表列包含 0 素材，已禁用 0)`
当文件的路径是“Mirai/data/PetPet/xmmt.dituon.petpet/” 返回的信息是：```
ヾ(≧▽≦*)o Petpet 初始化成功，使用 pet 以获取keyList!
无法读取 C:\Users\Administrator\Desktop\Mirai\data\PetPet\xmmt.dituon.petpet/data.json:

java.io.FileNotFoundException: C:\Users\Administrator\Desktop\Mirai\data\PetPet\xmmt.dituon.petpet\data.json (系统找不到指定的文件。)
Petpet 加载完毕 (共 0 素材，随机表列包含 0 素材，已禁用 0)
```

**Comment by Dituon** [comment]
![image](https://user-images.githubusercontent.com/68615161/197343697-5bcdbac5-a053-47d1-97e5-c9f2cd770657.png)
![image](https://user-images.githubusercontent.com/68615161/197343855-9173964b-bcb5-4b06-ade9-08a564d598ee.png)

`无法读取文件，请检查data目录` 的报错触发有三种可能:

1. jvm无法权限读取文件目录
2. `C:\Users\Administrator\Desktop\Mirai\data\xmmt.dituon.petpet\`目录为空
3. 插件配置文件中的错误配置导致排除了所有Data

**Comment by milanor1970** [comment]
> ![image](https://user-images.githubusercontent.com/68615161/197343697-5bcdbac5-a053-47d1-97e5-c9f2cd770657.png) ![image](https://user-images.githubusercontent.com/68615161/197343855-9173964b-bcb5-4b06-ade9-08a564d598ee.png)
> 
> `无法读取文件，请检查data目录` 的报错触发有三种可能:
> 
> 1. jvm无权限读取文件目录
> 2. `C:\Users\Administrator\Desktop\Mirai\data\xmmt.dituon.petpet\`目录为空
> 3. 插件配置文件中的错误配置导致排除了所有Data

但是当“Mirai/data/PetPet/xmmt.dituon.petpet/”这个路径下有文件的时候，输出的内容则是：
`ヾ(≧▽≦*)o Petpet 初始化成功，使用 pet 以获取keyList!
无法读取 C:\Users\Administrator\Desktop\Mirai\data\PetPet\xmmt.dituon.petpet/data.json:

java.io.FileNotFoundException: C:\Users\Administrator\Desktop\Mirai\data\PetPet\xmmt.dituon.petpet\data.json (系统找不到指定的文件。)`

**Comment by Dituon** [comment]
正确的目录应为`C:\Users\Administrator\Desktop\Mirai\data\xmmt.dituon.petpet\`

**Comment by milanor1970** [comment]
> 

上面说了，试过了......这样操作的结果是插件自动生成了一个“C:\Users\Administrator\Desktop\Mirai\data\PetPet\”的空目录。

**Comment by Dituon** [comment]
方便加一下交流群吗  我通过你的描述无法确定问题

**Comment by milanor1970** [comment]
好的，已申请

**Comment by Dituon** [comment]
对于`2.9`之前的版本, 可将`Mirai\data\xmmt.dituon.petpet\`更改为`Mirai\data\PetPet\`
