### ISSUE TITLE
Bugs ?

### ISSUE THREAD

**Issue by Scrohild** [Dituon/petpet#78]
"推"(生成一个人推雪球那个)生成的gif一闪一闪的, 转不起来

**Comment by Dituon** [comment]
无法复现, 请检查本地文件完整性, 提供详细信息 (如 Mirai版本, 插件版本, 插件配置, 模板文件 等)

**Comment by Scrohild** [comment]
oh好的, 呃, 我并不是bot搭建者, 回去我去反映反映.
我们群的bot就有问题, 后来我发现别的群的bot, 同样也是petpet插件的就没事儿, 那肯定是我们自己的问题了...抱歉打扰
