### ISSUE TITLE
报错 bound must be positive

### ISSUE THREAD

**Issue by NingLiu1998** [Dituon/petpet#85]
![image](https://user-images.githubusercontent.com/109678937/225319763-9b503b59-6643-4d09-abef-f85b0c1e56e9.png)

如图所示，今天刚拉的

![image](https://user-images.githubusercontent.com/109678937/225319946-41b52adc-1f7f-4e23-ae6a-95a571368acf.png)
这是图片素材目录

**Comment by NingLiu1998** [comment]
好，我找找

**Comment by yizhitian1145** [comment]
朋友你下载了data.zip吗，我把压缩包解压到mirai，重新启动后好了，之前也是你这种问题

**Comment by NingLiu1998** [comment]
> 朋友你下载了data.zip吗，我把压缩包解压到mirai，重新启动后好了，之前也是你这种问题

报错的时候data.aip是下好的

**Comment by NingLiu1998** [comment]
最新情况：由于QQ机器人突然登录不上，于是我查找了一番
在安装了  [临时性补丁](https://github.com/cssxsh/fix-protocol-version) 之后，机器人可以正常登录了，然后pet不知道为啥自己就自己好了。。。还是群友发现戳戳机器人可以发图片了
