### ISSUE TITLE
如何直接启动程序？

### ISSUE THREAD

**Issue by msojocs** [Dituon/petpet#87]
启动直接报错

![image](https://user-images.githubusercontent.com/20937135/227109291-dd30463a-a876-4485-8b49-2df8fd8a5b17.png)
![image](https://user-images.githubusercontent.com/20937135/227109347-6ff7b649-8486-4225-a23a-cd32515e48dc.png)

**Comment by msojocs** [comment]
![image](https://user-images.githubusercontent.com/20937135/227111400-360bdb3b-357a-4ab1-8517-e49bc4024339.png)
![image](https://user-images.githubusercontent.com/20937135/227111438-cf0be423-f506-48a9-a430-60663a59e45a.png)

**Comment by Dituon** [comment]
已修复, 建议使用`petpet-5.4.jar`
