### ISSUE TITLE
疑似命名错误？

### ISSUE THREAD

**Issue by msojocs** [Dituon/petpet#88]
是 `form` 不是 `from` ？
我觉得应该是 `from`

https://github.com/Dituon/petpet/blob/d431a832d0ac889a7087b5eab636aa4a6c61c5a9/src/main/java/moe/dituon/petpet/server/POSTParser.java#L12

另外出现错误希望能输出异常信息
错误的情况没有返回，找了好久才发现单词不太一样：
![image](https://user-images.githubusercontent.com/20937135/227219705-4ecbbdc1-0b17-4a5f-8d4d-1cfd7eb8576f.png)

**Comment by Dituon** [comment]
已修复, 万分感谢

1. 修复了命名错误
2. 添加了http错误返回
