### ISSUE TITLE
5.4版本似乎冷却时间失效了？

### ISSUE THREAD

**Issue by yuanbolin** [Dituon/petpet#89]
![image](https://user-images.githubusercontent.com/44077734/233279218-f48cc993-dd41-4bd4-918e-c90e05077028.png)

**Comment by Dituon** [comment]
不支持配置文件热重载，程序初始化时会将配置文件读取到内存中。
- 关闭程序后修改配置文件
或
- 修改配置文件后重启程序，确保配置文件已被正确保存

**Comment by yuanbolin** [comment]
额 我我更新插件版本时重启过的

**Comment by Dituon** [comment]
抱歉  文档说明有误, Cooler在 #81 后单位更改为 **毫秒**(此前为秒)

文档错误将在近期修复, 感谢您的反馈
