### ISSUE TITLE
[建议] 给TO枚举添加id

### ISSUE THREAD

**Issue by Zeroization** [Dituon/petpet#91]
刚上手，针对两个头像来源好像只能用`$TO`和`$FROM`，使用的时候可能会出现一些"bug"：
![image](https://github.com/Dituon/petpet/assets/47522897/ada3cc86-8d04-4635-8c19-4b522b2833b3)

但是全部使用`$TO`的话，会使得头像来源变得统一：
![image](https://github.com/Dituon/petpet/assets/47522897/be34e4ac-8788-40ae-93e6-69b433e3a9a3)

因此希望可以**给TO枚举添加id**（比如再添加一个`avatar.name`或`avatar,id`属性），以便区分头像来源

**Comment by Dituon** [comment]
`Plugin`: 消息中含有多张图片时, 第一张图片为`TO`, 最后一张为`FROM`

希望此特性能解决你的问题, 如果我误解了你的需求 欢迎再次回复

**Comment by Dituon** [comment]
新版本支持图像列表, 欢迎尝试
