### ISSUE TITLE
[FR] 在线编辑器中的Deform操作能否显示图片？

### ISSUE THREAD

**Issue by YuLiu-lab** [Dituon/petpet#95]
在线编辑器大大简化了表情包的制作，但是在使用Deform进行变形的时候看不到图片变成了什么样。
请问能否增加个开关在进行Deform的时候选择显示图片还是粉色框。

**Comment by Dituon** [comment]
https://github.com/Dituon/petpet-js
这是我用typescript重写的前端版本, 之后会考虑重写在线编辑器实现此功能

**Comment by Dituon** [comment]
https://d2n.moe/petpet-js/editor/
在线编辑器的重构版本, 使用了我的前端版本渲染预览，目前是测试状态，发现的问题会在近期修复

**Comment by YuLiu-lab** [comment]
> https://dituon.github.io/petpet-js/editor/ 在线编辑器的重构版本, 使用了我的前端版本渲染预览，目前是测试状态，发现的问题会在近期修复，届时会将本仓库的编辑器重定向至重构版本

谢谢！我试了一下，现在可以通过preview来查看Deform操作后的图片了。就是我在使用过程中发现，右侧最上方的图片框在页面下划过程中会全程固定显示，不知道这是特意的设定还是BUG。

**Comment by Dituon** [comment]
将编辑窗口规定在右上角是有意为之，便于「在更改左边设置的同时  在右边调整位置」

**Comment by YuLiu-lab** [comment]
> 将编辑窗口规定在右上角是有意为之，便于「在更改左边设置的同时 在右边调整位置」

好的，感谢大佬的付出。

**Comment by Dituon** [comment]
编辑器已基本完善，实现「所见即所得」，欢迎使用！

**Comment by YuLiu-lab** [comment]
> 编辑器已基本完善，实现「所见即所得」，欢迎使用！

感谢付出！试了一下，预览功能很好用！🤩
