### ISSUE TITLE
能否使同一个模板随机几个尺寸相同的背景图？

### ISSUE THREAD

**Issue by SyuueenN** [Dituon/petpet#96]
RT

**Comment by Dituon** [comment]
对于目录下有多个图片文件的IMG类型, 会随机读取一张作为背景

https://github.com/Dituon/petpet/blob/35680ef7cb434e2ae1dddcf8bd99bf133290e2d1/src/main/java/moe/dituon/petpet/share/BasePetService.java#L295

**Comment by Dituon** [comment]
文档已更新
